syntax = "proto3";

package proto;

option go_package = "ks-proto/pkg/pb";

import "code.proto";

// User 用户信息
message User {
  string id = 1;
  string name = 2;
  string email = 3;
  string avatar = 4;
}

message RegisterRequest {
  string name = 1;
  string email = 2;
  string password = 3;
  string verify_code = 5;
}

message RegisterResponse {
  ErrorCode code = 1;
  string msg = 2;
  User user = 3;
}

message SetAvatarRequest {
  string user_id = 1;
  string avatar = 2;
}

message SetAvatarResponse {
  ErrorCode code = 1;
  string msg = 2;
}

message VerifyCodeRequest {
  string email = 1;
}

message VerifyCodeResponse {
  ErrorCode code = 1;
  string msg = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  ErrorCode code = 1;
  string msg = 2;
  string access_token = 3;
  string refresh_token = 4;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  ErrorCode code = 1;
  string msg = 2;
}

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  ErrorCode code = 1;
  string msg = 2;
  string access_token = 3;
  string refresh_token = 4;
}

message GetUserRequest {
  string user_id = 1;
}

message GetUserResponse {
  ErrorCode code = 1;
  string msg = 2;
  User user = 3;
}

message ForgetPasswordRequest {
  string email = 1;
  string password = 2;
  string verify_code = 3;
}

message ForgetPasswordResponse {
  ErrorCode code = 1;
  string msg = 2;
}

message ResetPasswordRequest {
  string user_id = 1;
  string old_password = 2;
  string new_password = 3;
}

message ResetPasswordResponse {
  ErrorCode code = 1;
  string msg = 2;
}

message UpdateUserInfoRequest {
  User user = 1;
}

message UpdateUserInfoResponse {
  ErrorCode code = 1;
  string msg = 2;
  User user = 3;
}

message UnregisterRequest {
  string user_id = 1;
  string email = 2;
  string password = 3;
  string verify_code = 4;
}

message UnregisterResponse {
  ErrorCode code = 1;
  string msg = 2;
}

service UserService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc SetAvatar(SetAvatarRequest) returns (SetAvatarResponse);
  rpc VerifyCode(VerifyCodeRequest) returns (VerifyCodeResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc ForgetPassword(ForgetPasswordRequest) returns (ForgetPasswordResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc UpdateUserInfo(UpdateUserInfoRequest) returns (UpdateUserInfoResponse);
  rpc Unregister(UnregisterRequest) returns (UnregisterResponse);
}

