// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: proto/ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_Chat_FullMethodName                 = "/proto.AIService/Chat"
	AIService_Search_FullMethodName               = "/proto.AIService/Search"
	AIService_GetChatSessions_FullMethodName      = "/proto.AIService/GetChatSessions"
	AIService_GetChatMessages_FullMethodName      = "/proto.AIService/GetChatMessages"
	AIService_DeleteChatSession_FullMethodName    = "/proto.AIService/DeleteChatSession"
	AIService_UpdateRepoVisibility_FullMethodName = "/proto.AIService/UpdateRepoVisibility"
	AIService_VectorizeArticle_FullMethodName     = "/proto.AIService/VectorizeArticle"
	AIService_DeleteRepoVectors_FullMethodName    = "/proto.AIService/DeleteRepoVectors"
	AIService_DeleteFileVectors_FullMethodName    = "/proto.AIService/DeleteFileVectors"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	// Chat 流式对话（主要入口）
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	// Search 全文搜索
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// 会话管理
	GetChatSessions(ctx context.Context, in *GetChatSessionsRequest, opts ...grpc.CallOption) (*GetChatSessionsResponse, error)
	GetChatMessages(ctx context.Context, in *GetChatMessagesRequest, opts ...grpc.CallOption) (*GetChatMessagesResponse, error)
	DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*DeleteChatSessionResponse, error)
	// UpdateRepoVisibility 更新仓库可见性
	UpdateRepoVisibility(ctx context.Context, in *UpdateRepoVisibilityRequest, opts ...grpc.CallOption) (*UpdateRepoVisibilityResponse, error)
	// VectorizeArticle 向量化文章（异步）
	VectorizeArticle(ctx context.Context, in *VectorizeArticleRequest, opts ...grpc.CallOption) (*VectorizeArticleResponse, error)
	// DeleteRepoVectors 删除知识库向量数据
	DeleteRepoVectors(ctx context.Context, in *DeleteRepoVectorsRequest, opts ...grpc.CallOption) (*DeleteRepoVectorsResponse, error)
	// DeleteFileVectors 删除文件向量数据
	DeleteFileVectors(ctx context.Context, in *DeleteFileVectorsRequest, opts ...grpc.CallOption) (*DeleteFileVectorsResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *aIServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, AIService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetChatSessions(ctx context.Context, in *GetChatSessionsRequest, opts ...grpc.CallOption) (*GetChatSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatSessionsResponse)
	err := c.cc.Invoke(ctx, AIService_GetChatSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetChatMessages(ctx context.Context, in *GetChatMessagesRequest, opts ...grpc.CallOption) (*GetChatMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatMessagesResponse)
	err := c.cc.Invoke(ctx, AIService_GetChatMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*DeleteChatSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatSessionResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) UpdateRepoVisibility(ctx context.Context, in *UpdateRepoVisibilityRequest, opts ...grpc.CallOption) (*UpdateRepoVisibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRepoVisibilityResponse)
	err := c.cc.Invoke(ctx, AIService_UpdateRepoVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) VectorizeArticle(ctx context.Context, in *VectorizeArticleRequest, opts ...grpc.CallOption) (*VectorizeArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorizeArticleResponse)
	err := c.cc.Invoke(ctx, AIService_VectorizeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteRepoVectors(ctx context.Context, in *DeleteRepoVectorsRequest, opts ...grpc.CallOption) (*DeleteRepoVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRepoVectorsResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteRepoVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteFileVectors(ctx context.Context, in *DeleteFileVectorsRequest, opts ...grpc.CallOption) (*DeleteFileVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileVectorsResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteFileVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	// Chat 流式对话（主要入口）
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	// Search 全文搜索
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// 会话管理
	GetChatSessions(context.Context, *GetChatSessionsRequest) (*GetChatSessionsResponse, error)
	GetChatMessages(context.Context, *GetChatMessagesRequest) (*GetChatMessagesResponse, error)
	DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*DeleteChatSessionResponse, error)
	// UpdateRepoVisibility 更新仓库可见性
	UpdateRepoVisibility(context.Context, *UpdateRepoVisibilityRequest) (*UpdateRepoVisibilityResponse, error)
	// VectorizeArticle 向量化文章（异步）
	VectorizeArticle(context.Context, *VectorizeArticleRequest) (*VectorizeArticleResponse, error)
	// DeleteRepoVectors 删除知识库向量数据
	DeleteRepoVectors(context.Context, *DeleteRepoVectorsRequest) (*DeleteRepoVectorsResponse, error)
	// DeleteFileVectors 删除文件向量数据
	DeleteFileVectors(context.Context, *DeleteFileVectorsRequest) (*DeleteFileVectorsResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedAIServiceServer) GetChatSessions(context.Context, *GetChatSessionsRequest) (*GetChatSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatSessions not implemented")
}
func (UnimplementedAIServiceServer) GetChatMessages(context.Context, *GetChatMessagesRequest) (*GetChatMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatMessages not implemented")
}
func (UnimplementedAIServiceServer) DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*DeleteChatSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChatSession not implemented")
}
func (UnimplementedAIServiceServer) UpdateRepoVisibility(context.Context, *UpdateRepoVisibilityRequest) (*UpdateRepoVisibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepoVisibility not implemented")
}
func (UnimplementedAIServiceServer) VectorizeArticle(context.Context, *VectorizeArticleRequest) (*VectorizeArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorizeArticle not implemented")
}
func (UnimplementedAIServiceServer) DeleteRepoVectors(context.Context, *DeleteRepoVectorsRequest) (*DeleteRepoVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRepoVectors not implemented")
}
func (UnimplementedAIServiceServer) DeleteFileVectors(context.Context, *DeleteFileVectorsRequest) (*DeleteFileVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFileVectors not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _AIService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetChatSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetChatSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetChatSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetChatSessions(ctx, req.(*GetChatSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetChatMessages(ctx, req.(*GetChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteChatSession(ctx, req.(*DeleteChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_UpdateRepoVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepoVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).UpdateRepoVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_UpdateRepoVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).UpdateRepoVisibility(ctx, req.(*UpdateRepoVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_VectorizeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorizeArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).VectorizeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_VectorizeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).VectorizeArticle(ctx, req.(*VectorizeArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteRepoVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepoVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteRepoVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteRepoVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteRepoVectors(ctx, req.(*DeleteRepoVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteFileVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteFileVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteFileVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteFileVectors(ctx, req.(*DeleteFileVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _AIService_Search_Handler,
		},
		{
			MethodName: "GetChatSessions",
			Handler:    _AIService_GetChatSessions_Handler,
		},
		{
			MethodName: "GetChatMessages",
			Handler:    _AIService_GetChatMessages_Handler,
		},
		{
			MethodName: "DeleteChatSession",
			Handler:    _AIService_DeleteChatSession_Handler,
		},
		{
			MethodName: "UpdateRepoVisibility",
			Handler:    _AIService_UpdateRepoVisibility_Handler,
		},
		{
			MethodName: "VectorizeArticle",
			Handler:    _AIService_VectorizeArticle_Handler,
		},
		{
			MethodName: "DeleteRepoVectors",
			Handler:    _AIService_DeleteRepoVectors_Handler,
		},
		{
			MethodName: "DeleteFileVectors",
			Handler:    _AIService_DeleteFileVectors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ai.proto",
}
