// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode 错误码枚举
// 错误码定义规范：
// 0xx - 成功
// 4xx - 客户端错误（仿 HTTP 4xx）
// 5xx - 服务端错误（仿 HTTP 5xx）
// 6xx - 业务错误
// 9xx - 系统级错误
type ErrorCode int32

const (
	// 成功
	ErrorCode_SUCCESS ErrorCode = 0
	// ========== 客户端错误 (4xx) ==========
	ErrorCode_BAD_REQUEST          ErrorCode = 400 // 通用请求错误
	ErrorCode_UNAUTHORIZED         ErrorCode = 401 // 未认证
	ErrorCode_FORBIDDEN            ErrorCode = 403 // 无权限
	ErrorCode_NOT_FOUND            ErrorCode = 404 // 资源不存在
	ErrorCode_METHOD_NOT_ALLOWED   ErrorCode = 405 // 方法不允许
	ErrorCode_CONFLICT             ErrorCode = 409 // 资源冲突
	ErrorCode_GONE                 ErrorCode = 410 // 资源已删除
	ErrorCode_UNPROCESSABLE_ENTITY ErrorCode = 422 // 参数校验失败
	ErrorCode_TOO_MANY_REQUESTS    ErrorCode = 429 // 请求过于频繁
	// ========== 服务端错误 (5xx) ==========
	ErrorCode_INTERNAL_ERROR      ErrorCode = 500 // 内部服务器错误
	ErrorCode_NOT_IMPLEMENTED     ErrorCode = 501 // 功能未实现
	ErrorCode_BAD_GATEWAY         ErrorCode = 502 // 网关错误
	ErrorCode_SERVICE_UNAVAILABLE ErrorCode = 503 // 服务不可用
	ErrorCode_GATEWAY_TIMEOUT     ErrorCode = 504 // 网关超时
	// ========== 业务错误 (6xx) ==========
	// 用户相关 (600-619)
	ErrorCode_USER_NOT_FOUND      ErrorCode = 600
	ErrorCode_USER_DISABLED       ErrorCode = 601
	ErrorCode_USER_LOCKED         ErrorCode = 602
	ErrorCode_USER_ALREADY_EXISTS ErrorCode = 603
	// 认证相关 (620-639)
	ErrorCode_PASSWORD_ERROR    ErrorCode = 620
	ErrorCode_TOKEN_EXPIRED     ErrorCode = 621
	ErrorCode_TOKEN_INVALID     ErrorCode = 622
	ErrorCode_TOKEN_MISSING     ErrorCode = 623
	ErrorCode_PERMISSION_DENIED ErrorCode = 624
	// 资源相关 (640-659)
	ErrorCode_RESOURCE_NOT_FOUND      ErrorCode = 640
	ErrorCode_RESOURCE_ALREADY_EXISTS ErrorCode = 641
	ErrorCode_RESOURCE_BUSY           ErrorCode = 642
	ErrorCode_RESOURCE_EXHAUSTED      ErrorCode = 643
	// 操作相关 (660-679)
	ErrorCode_OPERATION_FAILED   ErrorCode = 660
	ErrorCode_OPERATION_TIMEOUT  ErrorCode = 661
	ErrorCode_OPERATION_CANCELED ErrorCode = 662
	// ========== 系统级错误 (9xx) ==========
	ErrorCode_DATABASE_ERROR    ErrorCode = 900
	ErrorCode_CACHE_ERROR       ErrorCode = 901
	ErrorCode_MQ_ERROR          ErrorCode = 902
	ErrorCode_THIRD_PARTY_ERROR ErrorCode = 903
	ErrorCode_CONFIG_ERROR      ErrorCode = 904
	ErrorCode_NETWORK_ERROR     ErrorCode = 905
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "SUCCESS",
		400: "BAD_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		405: "METHOD_NOT_ALLOWED",
		409: "CONFLICT",
		410: "GONE",
		422: "UNPROCESSABLE_ENTITY",
		429: "TOO_MANY_REQUESTS",
		500: "INTERNAL_ERROR",
		501: "NOT_IMPLEMENTED",
		502: "BAD_GATEWAY",
		503: "SERVICE_UNAVAILABLE",
		504: "GATEWAY_TIMEOUT",
		600: "USER_NOT_FOUND",
		601: "USER_DISABLED",
		602: "USER_LOCKED",
		603: "USER_ALREADY_EXISTS",
		620: "PASSWORD_ERROR",
		621: "TOKEN_EXPIRED",
		622: "TOKEN_INVALID",
		623: "TOKEN_MISSING",
		624: "PERMISSION_DENIED",
		640: "RESOURCE_NOT_FOUND",
		641: "RESOURCE_ALREADY_EXISTS",
		642: "RESOURCE_BUSY",
		643: "RESOURCE_EXHAUSTED",
		660: "OPERATION_FAILED",
		661: "OPERATION_TIMEOUT",
		662: "OPERATION_CANCELED",
		900: "DATABASE_ERROR",
		901: "CACHE_ERROR",
		902: "MQ_ERROR",
		903: "THIRD_PARTY_ERROR",
		904: "CONFIG_ERROR",
		905: "NETWORK_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":                 0,
		"BAD_REQUEST":             400,
		"UNAUTHORIZED":            401,
		"FORBIDDEN":               403,
		"NOT_FOUND":               404,
		"METHOD_NOT_ALLOWED":      405,
		"CONFLICT":                409,
		"GONE":                    410,
		"UNPROCESSABLE_ENTITY":    422,
		"TOO_MANY_REQUESTS":       429,
		"INTERNAL_ERROR":          500,
		"NOT_IMPLEMENTED":         501,
		"BAD_GATEWAY":             502,
		"SERVICE_UNAVAILABLE":     503,
		"GATEWAY_TIMEOUT":         504,
		"USER_NOT_FOUND":          600,
		"USER_DISABLED":           601,
		"USER_LOCKED":             602,
		"USER_ALREADY_EXISTS":     603,
		"PASSWORD_ERROR":          620,
		"TOKEN_EXPIRED":           621,
		"TOKEN_INVALID":           622,
		"TOKEN_MISSING":           623,
		"PERMISSION_DENIED":       624,
		"RESOURCE_NOT_FOUND":      640,
		"RESOURCE_ALREADY_EXISTS": 641,
		"RESOURCE_BUSY":           642,
		"RESOURCE_EXHAUSTED":      643,
		"OPERATION_FAILED":        660,
		"OPERATION_TIMEOUT":       661,
		"OPERATION_CANCELED":      662,
		"DATABASE_ERROR":          900,
		"CACHE_ERROR":             901,
		"MQ_ERROR":                902,
		"THIRD_PARTY_ERROR":       903,
		"CONFIG_ERROR":            904,
		"NETWORK_ERROR":           905,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{0}
}

var File_code_proto protoreflect.FileDescriptor

const file_code_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"code.proto\x12\x05proto*\x8f\x06\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\x17\n" +
	"\x12METHOD_NOT_ALLOWED\x10\x95\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\t\n" +
	"\x04GONE\x10\x9a\x03\x12\x19\n" +
	"\x14UNPROCESSABLE_ENTITY\x10\xa6\x03\x12\x16\n" +
	"\x11TOO_MANY_REQUESTS\x10\xad\x03\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x14\n" +
	"\x0fNOT_IMPLEMENTED\x10\xf5\x03\x12\x10\n" +
	"\vBAD_GATEWAY\x10\xf6\x03\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x14\n" +
	"\x0fGATEWAY_TIMEOUT\x10\xf8\x03\x12\x13\n" +
	"\x0eUSER_NOT_FOUND\x10\xd8\x04\x12\x12\n" +
	"\rUSER_DISABLED\x10\xd9\x04\x12\x10\n" +
	"\vUSER_LOCKED\x10\xda\x04\x12\x18\n" +
	"\x13USER_ALREADY_EXISTS\x10\xdb\x04\x12\x13\n" +
	"\x0ePASSWORD_ERROR\x10\xec\x04\x12\x12\n" +
	"\rTOKEN_EXPIRED\x10\xed\x04\x12\x12\n" +
	"\rTOKEN_INVALID\x10\xee\x04\x12\x12\n" +
	"\rTOKEN_MISSING\x10\xef\x04\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\xf0\x04\x12\x17\n" +
	"\x12RESOURCE_NOT_FOUND\x10\x80\x05\x12\x1c\n" +
	"\x17RESOURCE_ALREADY_EXISTS\x10\x81\x05\x12\x12\n" +
	"\rRESOURCE_BUSY\x10\x82\x05\x12\x17\n" +
	"\x12RESOURCE_EXHAUSTED\x10\x83\x05\x12\x15\n" +
	"\x10OPERATION_FAILED\x10\x94\x05\x12\x16\n" +
	"\x11OPERATION_TIMEOUT\x10\x95\x05\x12\x17\n" +
	"\x12OPERATION_CANCELED\x10\x96\x05\x12\x13\n" +
	"\x0eDATABASE_ERROR\x10\x84\a\x12\x10\n" +
	"\vCACHE_ERROR\x10\x85\a\x12\r\n" +
	"\bMQ_ERROR\x10\x86\a\x12\x16\n" +
	"\x11THIRD_PARTY_ERROR\x10\x87\a\x12\x11\n" +
	"\fCONFIG_ERROR\x10\x88\a\x12\x12\n" +
	"\rNETWORK_ERROR\x10\x89\aB\x11Z\x0fks-proto/pkg/pbb\x06proto3"

var (
	file_code_proto_rawDescOnce sync.Once
	file_code_proto_rawDescData []byte
)

func file_code_proto_rawDescGZIP() []byte {
	file_code_proto_rawDescOnce.Do(func() {
		file_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)))
	})
	return file_code_proto_rawDescData
}

var file_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: proto.ErrorCode
}
var file_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_init() }
func file_code_proto_init() {
	if File_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_proto_goTypes,
		DependencyIndexes: file_code_proto_depIdxs,
		EnumInfos:         file_code_proto_enumTypes,
	}.Build()
	File_code_proto = out.File
	file_code_proto_goTypes = nil
	file_code_proto_depIdxs = nil
}
