// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: repo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RepoVisibility 仓库可见性枚举
type RepoVisibility int32

const (
	RepoVisibility_UNSPECIFIED RepoVisibility = 0
	RepoVisibility_PUBLIC      RepoVisibility = 1
	RepoVisibility_PRIVATE     RepoVisibility = 2
)

// Enum value maps for RepoVisibility.
var (
	RepoVisibility_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PUBLIC",
		2: "PRIVATE",
	}
	RepoVisibility_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PUBLIC":      1,
		"PRIVATE":     2,
	}
)

func (x RepoVisibility) Enum() *RepoVisibility {
	p := new(RepoVisibility)
	*p = x
	return p
}

func (x RepoVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepoVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_repo_proto_enumTypes[0].Descriptor()
}

func (RepoVisibility) Type() protoreflect.EnumType {
	return &file_repo_proto_enumTypes[0]
}

func (x RepoVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepoVisibility.Descriptor instead.
func (RepoVisibility) EnumDescriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    RepoVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_UNSPECIFIED
}

func (x *Repo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoId        string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Node) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CreateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    RepoVisibility         `protobuf:"varint,3,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoRequest) Reset() {
	*x = CreateRepoRequest{}
	mi := &file_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoRequest) ProtoMessage() {}

func (x *CreateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoRequest.ProtoReflect.Descriptor instead.
func (*CreateRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRepoRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepoRequest) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_UNSPECIFIED
}

func (x *CreateRepoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoResponse) Reset() {
	*x = CreateRepoResponse{}
	mi := &file_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoResponse) ProtoMessage() {}

func (x *CreateRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoResponse.ProtoReflect.Descriptor instead.
func (*CreateRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepoRequest) Reset() {
	*x = DeleteRepoRequest{}
	mi := &file_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepoRequest) ProtoMessage() {}

func (x *DeleteRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepoRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type DeleteRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedNodes  []*Node                `protobuf:"bytes,2,rep,name=deleted_nodes,json=deletedNodes,proto3" json:"deleted_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepoResponse) Reset() {
	*x = DeleteRepoResponse{}
	mi := &file_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepoResponse) ProtoMessage() {}

func (x *DeleteRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepoResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRepoResponse) GetDeletedNodes() []*Node {
	if x != nil {
		return x.DeletedNodes
	}
	return nil
}

type GetMyReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReposRequest) Reset() {
	*x = GetMyReposRequest{}
	mi := &file_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReposRequest) ProtoMessage() {}

func (x *GetMyReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReposRequest.ProtoReflect.Descriptor instead.
func (*GetMyReposRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyReposRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetMyReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Repos         []*Repo                `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReposResponse) Reset() {
	*x = GetMyReposResponse{}
	mi := &file_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReposResponse) ProtoMessage() {}

func (x *GetMyReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReposResponse.ProtoReflect.Descriptor instead.
func (*GetMyReposResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{7}
}

func (x *GetMyReposResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMyReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type GetReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoIds       []string               `protobuf:"bytes,1,rep,name=repo_ids,json=repoIds,proto3" json:"repo_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposRequest) Reset() {
	*x = GetReposRequest{}
	mi := &file_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposRequest) ProtoMessage() {}

func (x *GetReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposRequest.ProtoReflect.Descriptor instead.
func (*GetReposRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{8}
}

func (x *GetReposRequest) GetRepoIds() []string {
	if x != nil {
		return x.RepoIds
	}
	return nil
}

type GetReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Repos         []*Repo                `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposResponse) Reset() {
	*x = GetReposResponse{}
	mi := &file_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposResponse) ProtoMessage() {}

func (x *GetReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposResponse.ProtoReflect.Descriptor instead.
func (*GetReposResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{9}
}

func (x *GetReposResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNodeRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UploadArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArticleRequest) Reset() {
	*x = UploadArticleRequest{}
	mi := &file_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArticleRequest) ProtoMessage() {}

func (x *UploadArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArticleRequest.ProtoReflect.Descriptor instead.
func (*UploadArticleRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{12}
}

func (x *UploadArticleRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UploadArticleRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UploadArticleRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"` // 旧文件路径，用于删除 MinIO 和 Milvus 中的旧数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArticleResponse) Reset() {
	*x = UploadArticleResponse{}
	mi := &file_repo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArticleResponse) ProtoMessage() {}

func (x *UploadArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArticleResponse.ProtoReflect.Descriptor instead.
func (*UploadArticleResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{13}
}

func (x *UploadArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadArticleResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *UploadArticleResponse) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_repo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{14}
}

func (x *GetNodesRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_repo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{15}
}

func (x *GetNodesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_repo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteNodeRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_repo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RenameNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameNodeRequest) Reset() {
	*x = RenameNodeRequest{}
	mi := &file_repo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameNodeRequest) ProtoMessage() {}

func (x *RenameNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameNodeRequest.ProtoReflect.Descriptor instead.
func (*RenameNodeRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{18}
}

func (x *RenameNodeRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *RenameNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenameNodeRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameNodeResponse) Reset() {
	*x = RenameNodeResponse{}
	mi := &file_repo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameNodeResponse) ProtoMessage() {}

func (x *RenameNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameNodeResponse.ProtoReflect.Descriptor instead.
func (*RenameNodeResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{19}
}

func (x *RenameNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenameNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 可选，不传则不修改
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                          // 可选，不传则不修改
	Visibility    RepoVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"` // 可选，不传则不修改
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoRequest) Reset() {
	*x = UpdateRepoRequest{}
	mi := &file_repo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoRequest) ProtoMessage() {}

func (x *UpdateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *UpdateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRepoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRepoRequest) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_UNSPECIFIED
}

type UpdateRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Repo          *Repo                  `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoResponse) Reset() {
	*x = UpdateRepoResponse{}
	mi := &file_repo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoResponse) ProtoMessage() {}

func (x *UpdateRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoResponse.ProtoReflect.Descriptor instead.
func (*UpdateRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

var File_repo_proto protoreflect.FileDescriptor

const file_repo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"repo.proto\x12\x05proto\"\x9e\x01\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"m\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\x9b\x01\n" +
	"\x11CreateRepoRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\".\n" +
	"\x12CreateRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11DeleteRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\"`\n" +
	"\x12DeleteRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\rdeleted_nodes\x18\x02 \x03(\v2\v.proto.NodeR\fdeletedNodes\".\n" +
	"\x11GetMyReposRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"Q\n" +
	"\x12GetMyReposResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05repos\x18\x02 \x03(\v2\v.proto.RepoR\x05repos\",\n" +
	"\x0fGetReposRequest\x12\x19\n" +
	"\brepo_ids\x18\x01 \x03(\tR\arepoIds\"O\n" +
	"\x10GetReposResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05repos\x18\x02 \x03(\v2\v.proto.RepoR\x05repos\"@\n" +
	"\x11CreateNodeRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x12CreateNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.proto.NodeR\x04node\"Y\n" +
	"\x14UploadArticleRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"o\n" +
	"\x15UploadArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.proto.NodeR\x04node\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\"*\n" +
	"\x0fGetNodesRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\"O\n" +
	"\x10GetNodesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05nodes\x18\x02 \x03(\v2\v.proto.NodeR\x05nodes\"E\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"O\n" +
	"\x12DeleteNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.proto.NodeR\x04node\"`\n" +
	"\x11RenameNodeRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"O\n" +
	"\x12RenameNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.proto.NodeR\x04node\"\x99\x01\n" +
	"\x11UpdateRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\"O\n" +
	"\x12UpdateRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\x04repo\x18\x02 \x01(\v2\v.proto.RepoR\x04repo*:\n" +
	"\x0eRepoVisibility\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\v\n" +
	"\aPRIVATE\x10\x022\xa8\x05\n" +
	"\vRepoService\x12A\n" +
	"\n" +
	"CreateRepo\x12\x18.proto.CreateRepoRequest\x1a\x19.proto.CreateRepoResponse\x12A\n" +
	"\n" +
	"DeleteRepo\x12\x18.proto.DeleteRepoRequest\x1a\x19.proto.DeleteRepoResponse\x12A\n" +
	"\n" +
	"GetMyRepos\x12\x18.proto.GetMyReposRequest\x1a\x19.proto.GetMyReposResponse\x12;\n" +
	"\bGetRepos\x12\x16.proto.GetReposRequest\x1a\x17.proto.GetReposResponse\x12A\n" +
	"\n" +
	"CreateNode\x12\x18.proto.CreateNodeRequest\x1a\x19.proto.CreateNodeResponse\x12J\n" +
	"\rUploadArticle\x12\x1b.proto.UploadArticleRequest\x1a\x1c.proto.UploadArticleResponse\x12;\n" +
	"\bGetNodes\x12\x16.proto.GetNodesRequest\x1a\x17.proto.GetNodesResponse\x12A\n" +
	"\n" +
	"DeleteNode\x12\x18.proto.DeleteNodeRequest\x1a\x19.proto.DeleteNodeResponse\x12A\n" +
	"\n" +
	"RenameNode\x12\x18.proto.RenameNodeRequest\x1a\x19.proto.RenameNodeResponse\x12A\n" +
	"\n" +
	"UpdateRepo\x12\x18.proto.UpdateRepoRequest\x1a\x19.proto.UpdateRepoResponseB\x11Z\x0fks-proto/pkg/pbb\x06proto3"

var (
	file_repo_proto_rawDescOnce sync.Once
	file_repo_proto_rawDescData []byte
)

func file_repo_proto_rawDescGZIP() []byte {
	file_repo_proto_rawDescOnce.Do(func() {
		file_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)))
	})
	return file_repo_proto_rawDescData
}

var file_repo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_repo_proto_goTypes = []any{
	(RepoVisibility)(0),           // 0: proto.RepoVisibility
	(*Repo)(nil),                  // 1: proto.Repo
	(*Node)(nil),                  // 2: proto.Node
	(*CreateRepoRequest)(nil),     // 3: proto.CreateRepoRequest
	(*CreateRepoResponse)(nil),    // 4: proto.CreateRepoResponse
	(*DeleteRepoRequest)(nil),     // 5: proto.DeleteRepoRequest
	(*DeleteRepoResponse)(nil),    // 6: proto.DeleteRepoResponse
	(*GetMyReposRequest)(nil),     // 7: proto.GetMyReposRequest
	(*GetMyReposResponse)(nil),    // 8: proto.GetMyReposResponse
	(*GetReposRequest)(nil),       // 9: proto.GetReposRequest
	(*GetReposResponse)(nil),      // 10: proto.GetReposResponse
	(*CreateNodeRequest)(nil),     // 11: proto.CreateNodeRequest
	(*CreateNodeResponse)(nil),    // 12: proto.CreateNodeResponse
	(*UploadArticleRequest)(nil),  // 13: proto.UploadArticleRequest
	(*UploadArticleResponse)(nil), // 14: proto.UploadArticleResponse
	(*GetNodesRequest)(nil),       // 15: proto.GetNodesRequest
	(*GetNodesResponse)(nil),      // 16: proto.GetNodesResponse
	(*DeleteNodeRequest)(nil),     // 17: proto.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),    // 18: proto.DeleteNodeResponse
	(*RenameNodeRequest)(nil),     // 19: proto.RenameNodeRequest
	(*RenameNodeResponse)(nil),    // 20: proto.RenameNodeResponse
	(*UpdateRepoRequest)(nil),     // 21: proto.UpdateRepoRequest
	(*UpdateRepoResponse)(nil),    // 22: proto.UpdateRepoResponse
}
var file_repo_proto_depIdxs = []int32{
	0,  // 0: proto.Repo.visibility:type_name -> proto.RepoVisibility
	0,  // 1: proto.CreateRepoRequest.visibility:type_name -> proto.RepoVisibility
	2,  // 2: proto.DeleteRepoResponse.deleted_nodes:type_name -> proto.Node
	1,  // 3: proto.GetMyReposResponse.repos:type_name -> proto.Repo
	1,  // 4: proto.GetReposResponse.repos:type_name -> proto.Repo
	2,  // 5: proto.CreateNodeResponse.node:type_name -> proto.Node
	2,  // 6: proto.UploadArticleResponse.node:type_name -> proto.Node
	2,  // 7: proto.GetNodesResponse.nodes:type_name -> proto.Node
	2,  // 8: proto.DeleteNodeResponse.node:type_name -> proto.Node
	2,  // 9: proto.RenameNodeResponse.node:type_name -> proto.Node
	0,  // 10: proto.UpdateRepoRequest.visibility:type_name -> proto.RepoVisibility
	1,  // 11: proto.UpdateRepoResponse.repo:type_name -> proto.Repo
	3,  // 12: proto.RepoService.CreateRepo:input_type -> proto.CreateRepoRequest
	5,  // 13: proto.RepoService.DeleteRepo:input_type -> proto.DeleteRepoRequest
	7,  // 14: proto.RepoService.GetMyRepos:input_type -> proto.GetMyReposRequest
	9,  // 15: proto.RepoService.GetRepos:input_type -> proto.GetReposRequest
	11, // 16: proto.RepoService.CreateNode:input_type -> proto.CreateNodeRequest
	13, // 17: proto.RepoService.UploadArticle:input_type -> proto.UploadArticleRequest
	15, // 18: proto.RepoService.GetNodes:input_type -> proto.GetNodesRequest
	17, // 19: proto.RepoService.DeleteNode:input_type -> proto.DeleteNodeRequest
	19, // 20: proto.RepoService.RenameNode:input_type -> proto.RenameNodeRequest
	21, // 21: proto.RepoService.UpdateRepo:input_type -> proto.UpdateRepoRequest
	4,  // 22: proto.RepoService.CreateRepo:output_type -> proto.CreateRepoResponse
	6,  // 23: proto.RepoService.DeleteRepo:output_type -> proto.DeleteRepoResponse
	8,  // 24: proto.RepoService.GetMyRepos:output_type -> proto.GetMyReposResponse
	10, // 25: proto.RepoService.GetRepos:output_type -> proto.GetReposResponse
	12, // 26: proto.RepoService.CreateNode:output_type -> proto.CreateNodeResponse
	14, // 27: proto.RepoService.UploadArticle:output_type -> proto.UploadArticleResponse
	16, // 28: proto.RepoService.GetNodes:output_type -> proto.GetNodesResponse
	18, // 29: proto.RepoService.DeleteNode:output_type -> proto.DeleteNodeResponse
	20, // 30: proto.RepoService.RenameNode:output_type -> proto.RenameNodeResponse
	22, // 31: proto.RepoService.UpdateRepo:output_type -> proto.UpdateRepoResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_repo_proto_init() }
func file_repo_proto_init() {
	if File_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_proto_goTypes,
		DependencyIndexes: file_repo_proto_depIdxs,
		EnumInfos:         file_repo_proto_enumTypes,
		MessageInfos:      file_repo_proto_msgTypes,
	}.Build()
	File_repo_proto = out.File
	file_repo_proto_goTypes = nil
	file_repo_proto_depIdxs = nil
}
