// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: repo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoVisibility int32

const (
	RepoVisibility_REPO_VISIBILITY_UNSPECIFIED RepoVisibility = 0
	RepoVisibility_PUBLIC                      RepoVisibility = 1
	RepoVisibility_PRIVATE                     RepoVisibility = 2
)

// Enum value maps for RepoVisibility.
var (
	RepoVisibility_name = map[int32]string{
		0: "REPO_VISIBILITY_UNSPECIFIED",
		1: "PUBLIC",
		2: "PRIVATE",
	}
	RepoVisibility_value = map[string]int32{
		"REPO_VISIBILITY_UNSPECIFIED": 0,
		"PUBLIC":                      1,
		"PRIVATE":                     2,
	}
)

func (x RepoVisibility) Enum() *RepoVisibility {
	p := new(RepoVisibility)
	*p = x
	return p
}

func (x RepoVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepoVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_repo_proto_enumTypes[0].Descriptor()
}

func (RepoVisibility) Type() protoreflect.EnumType {
	return &file_repo_proto_enumTypes[0]
}

func (x RepoVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepoVisibility.Descriptor instead.
func (RepoVisibility) EnumDescriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

type CollaboratorRole int32

const (
	CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED CollaboratorRole = 0
	CollaboratorRole_ADMIN                         CollaboratorRole = 1
	CollaboratorRole_DEVELOPER                     CollaboratorRole = 2
	CollaboratorRole_VIEWER                        CollaboratorRole = 3
)

// Enum value maps for CollaboratorRole.
var (
	CollaboratorRole_name = map[int32]string{
		0: "COLLABORATOR_ROLE_UNSPECIFIED",
		1: "ADMIN",
		2: "DEVELOPER",
		3: "VIEWER",
	}
	CollaboratorRole_value = map[string]int32{
		"COLLABORATOR_ROLE_UNSPECIFIED": 0,
		"ADMIN":                         1,
		"DEVELOPER":                     2,
		"VIEWER":                        3,
	}
)

func (x CollaboratorRole) Enum() *CollaboratorRole {
	p := new(CollaboratorRole)
	*p = x
	return p
}

func (x CollaboratorRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollaboratorRole) Descriptor() protoreflect.EnumDescriptor {
	return file_repo_proto_enumTypes[1].Descriptor()
}

func (CollaboratorRole) Type() protoreflect.EnumType {
	return &file_repo_proto_enumTypes[1]
}

func (x CollaboratorRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollaboratorRole.Descriptor instead.
func (CollaboratorRole) EnumDescriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{1}
}

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    RepoVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ArticleCount  int64                  `protobuf:"varint,6,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_REPO_VISIBILITY_UNSPECIFIED
}

func (x *Repo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repo) GetArticleCount() int64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *Repo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Repo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Collaborator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,3,opt,name=role,proto3,enum=proto.CollaboratorRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	mi := &file_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{1}
}

func (x *Collaborator) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Collaborator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Collaborator) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

type CreateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    RepoVisibility         `protobuf:"varint,3,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoRequest) Reset() {
	*x = CreateRepoRequest{}
	mi := &file_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoRequest) ProtoMessage() {}

func (x *CreateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoRequest.ProtoReflect.Descriptor instead.
func (*CreateRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRepoRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepoRequest) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_REPO_VISIBILITY_UNSPECIFIED
}

func (x *CreateRepoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Repo          *Repo                  `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoResponse) Reset() {
	*x = CreateRepoResponse{}
	mi := &file_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoResponse) ProtoMessage() {}

func (x *CreateRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoResponse.ProtoReflect.Descriptor instead.
func (*CreateRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRepoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type GetRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRequest) Reset() {
	*x = GetRepoRequest{}
	mi := &file_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRequest) ProtoMessage() {}

func (x *GetRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{4}
}

func (x *GetRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *GetRepoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Repo          *Repo                  `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	MyRole        CollaboratorRole       `protobuf:"varint,4,opt,name=my_role,json=myRole,proto3,enum=proto.CollaboratorRole" json:"my_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoResponse) Reset() {
	*x = GetRepoResponse{}
	mi := &file_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoResponse) ProtoMessage() {}

func (x *GetRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoResponse.ProtoReflect.Descriptor instead.
func (*GetRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{5}
}

func (x *GetRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRepoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetRepoResponse) GetMyRole() CollaboratorRole {
	if x != nil {
		return x.MyRole
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

type UpdateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    RepoVisibility         `protobuf:"varint,5,opt,name=visibility,proto3,enum=proto.RepoVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoRequest) Reset() {
	*x = UpdateRepoRequest{}
	mi := &file_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoRequest) ProtoMessage() {}

func (x *UpdateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *UpdateRepoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRepoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRepoRequest) GetVisibility() RepoVisibility {
	if x != nil {
		return x.Visibility
	}
	return RepoVisibility_REPO_VISIBILITY_UNSPECIFIED
}

type UpdateRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Repo          *Repo                  `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoResponse) Reset() {
	*x = UpdateRepoResponse{}
	mi := &file_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoResponse) ProtoMessage() {}

func (x *UpdateRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoResponse.ProtoReflect.Descriptor instead.
func (*UpdateRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRepoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateRepoResponse) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type DeleteRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepoRequest) Reset() {
	*x = DeleteRepoRequest{}
	mi := &file_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepoRequest) ProtoMessage() {}

func (x *DeleteRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepoRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *DeleteRepoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepoResponse) Reset() {
	*x = DeleteRepoResponse{}
	mi := &file_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepoResponse) ProtoMessage() {}

func (x *DeleteRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepoResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRepoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListUserReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReposRequest) Reset() {
	*x = ListUserReposRequest{}
	mi := &file_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReposRequest) ProtoMessage() {}

func (x *ListUserReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReposRequest.ProtoReflect.Descriptor instead.
func (*ListUserReposRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserReposRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPublicReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicReposRequest) Reset() {
	*x = ListPublicReposRequest{}
	mi := &file_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicReposRequest) ProtoMessage() {}

func (x *ListPublicReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicReposRequest.ProtoReflect.Descriptor instead.
func (*ListPublicReposRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{11}
}

type ListPublicReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Repos         []*Repo                `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicReposResponse) Reset() {
	*x = ListPublicReposResponse{}
	mi := &file_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicReposResponse) ProtoMessage() {}

func (x *ListPublicReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicReposResponse.ProtoReflect.Descriptor instead.
func (*ListPublicReposResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{12}
}

func (x *ListPublicReposResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListPublicReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type ListUserReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Repos         []*Repo                `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReposResponse) Reset() {
	*x = ListUserReposResponse{}
	mi := &file_repo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReposResponse) ProtoMessage() {}

func (x *ListUserReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReposResponse.ProtoReflect.Descriptor instead.
func (*ListUserReposResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserReposResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListUserReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type AddCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,4,opt,name=role,proto3,enum=proto.CollaboratorRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollaboratorRequest) Reset() {
	*x = AddCollaboratorRequest{}
	mi := &file_repo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollaboratorRequest) ProtoMessage() {}

func (x *AddCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*AddCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{14}
}

func (x *AddCollaboratorRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

type AddCollaboratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollaboratorResponse) Reset() {
	*x = AddCollaboratorResponse{}
	mi := &file_repo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollaboratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollaboratorResponse) ProtoMessage() {}

func (x *AddCollaboratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollaboratorResponse.ProtoReflect.Descriptor instead.
func (*AddCollaboratorResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{15}
}

func (x *AddCollaboratorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCollaboratorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          CollaboratorRole       `protobuf:"varint,4,opt,name=role,proto3,enum=proto.CollaboratorRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollaboratorRequest) Reset() {
	*x = UpdateCollaboratorRequest{}
	mi := &file_repo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollaboratorRequest) ProtoMessage() {}

func (x *UpdateCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCollaboratorRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetRole() CollaboratorRole {
	if x != nil {
		return x.Role
	}
	return CollaboratorRole_COLLABORATOR_ROLE_UNSPECIFIED
}

type UpdateCollaboratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollaboratorResponse) Reset() {
	*x = UpdateCollaboratorResponse{}
	mi := &file_repo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollaboratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollaboratorResponse) ProtoMessage() {}

func (x *UpdateCollaboratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollaboratorResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollaboratorResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCollaboratorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCollaboratorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RemoveCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollaboratorRequest) Reset() {
	*x = RemoveCollaboratorRequest{}
	mi := &file_repo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollaboratorRequest) ProtoMessage() {}

func (x *RemoveCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveCollaboratorRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *RemoveCollaboratorRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *RemoveCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveCollaboratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollaboratorResponse) Reset() {
	*x = RemoveCollaboratorResponse{}
	mi := &file_repo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollaboratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollaboratorResponse) ProtoMessage() {}

func (x *RemoveCollaboratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollaboratorResponse.ProtoReflect.Descriptor instead.
func (*RemoveCollaboratorResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveCollaboratorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveCollaboratorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListCollaboratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollaboratorsRequest) Reset() {
	*x = ListCollaboratorsRequest{}
	mi := &file_repo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollaboratorsRequest) ProtoMessage() {}

func (x *ListCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*ListCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{20}
}

func (x *ListCollaboratorsRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ListCollaboratorsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListCollaboratorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Collaborators []*Collaborator        `protobuf:"bytes,2,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollaboratorsResponse) Reset() {
	*x = ListCollaboratorsResponse{}
	mi := &file_repo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollaboratorsResponse) ProtoMessage() {}

func (x *ListCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*ListCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{21}
}

func (x *ListCollaboratorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListCollaboratorsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

var File_repo_proto protoreflect.FileDescriptor

const file_repo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"repo.proto\x12\x05proto\"\x81\x02\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rarticle_count\x18\x06 \x01(\x03R\farticleCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"m\n" +
	"\fCollaborator\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.proto.CollaboratorRoleR\x04role\"\x9b\x01\n" +
	"\x11CreateRepoRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"a\n" +
	"\x12CreateRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x04repo\x18\x03 \x01(\v2\v.proto.RepoR\x04repo\"B\n" +
	"\x0eGetRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x90\x01\n" +
	"\x0fGetRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x04repo\x18\x03 \x01(\v2\v.proto.RepoR\x04repo\x120\n" +
	"\amy_role\x18\x04 \x01(\x0e2\x17.proto.CollaboratorRoleR\x06myRole\"\xb2\x01\n" +
	"\x11UpdateRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x15.proto.RepoVisibilityR\n" +
	"visibility\"a\n" +
	"\x12UpdateRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x04repo\x18\x03 \x01(\v2\v.proto.RepoR\x04repo\"E\n" +
	"\x11DeleteRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x12DeleteRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"/\n" +
	"\x14ListUserReposRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x18\n" +
	"\x16ListPublicReposRequest\"V\n" +
	"\x17ListPublicReposResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05repos\x18\x02 \x03(\v2\v.proto.RepoR\x05repos\"T\n" +
	"\x15ListUserReposResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05repos\x18\x02 \x03(\v2\v.proto.RepoR\x05repos\"\x98\x01\n" +
	"\x16AddCollaboratorRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x04 \x01(\x0e2\x17.proto.CollaboratorRoleR\x04role\"E\n" +
	"\x17AddCollaboratorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x9b\x01\n" +
	"\x19UpdateCollaboratorRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x04 \x01(\x0e2\x17.proto.CollaboratorRoleR\x04role\"H\n" +
	"\x1aUpdateCollaboratorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"n\n" +
	"\x19RemoveCollaboratorRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"H\n" +
	"\x1aRemoveCollaboratorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"L\n" +
	"\x18ListCollaboratorsRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x19ListCollaboratorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\rcollaborators\x18\x02 \x03(\v2\x13.proto.CollaboratorR\rcollaborators*J\n" +
	"\x0eRepoVisibility\x12\x1f\n" +
	"\x1bREPO_VISIBILITY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\v\n" +
	"\aPRIVATE\x10\x02*[\n" +
	"\x10CollaboratorRole\x12!\n" +
	"\x1dCOLLABORATOR_ROLE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\r\n" +
	"\tDEVELOPER\x10\x02\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x032\x8e\x06\n" +
	"\vRepoService\x12A\n" +
	"\n" +
	"CreateRepo\x12\x18.proto.CreateRepoRequest\x1a\x19.proto.CreateRepoResponse\x128\n" +
	"\aGetRepo\x12\x15.proto.GetRepoRequest\x1a\x16.proto.GetRepoResponse\x12A\n" +
	"\n" +
	"UpdateRepo\x12\x18.proto.UpdateRepoRequest\x1a\x19.proto.UpdateRepoResponse\x12A\n" +
	"\n" +
	"DeleteRepo\x12\x18.proto.DeleteRepoRequest\x1a\x19.proto.DeleteRepoResponse\x12J\n" +
	"\rListUserRepos\x12\x1b.proto.ListUserReposRequest\x1a\x1c.proto.ListUserReposResponse\x12P\n" +
	"\x0fListPublicRepos\x12\x1d.proto.ListPublicReposRequest\x1a\x1e.proto.ListPublicReposResponse\x12P\n" +
	"\x0fAddCollaborator\x12\x1d.proto.AddCollaboratorRequest\x1a\x1e.proto.AddCollaboratorResponse\x12Y\n" +
	"\x12UpdateCollaborator\x12 .proto.UpdateCollaboratorRequest\x1a!.proto.UpdateCollaboratorResponse\x12Y\n" +
	"\x12RemoveCollaborator\x12 .proto.RemoveCollaboratorRequest\x1a!.proto.RemoveCollaboratorResponse\x12V\n" +
	"\x11ListCollaborators\x12\x1f.proto.ListCollaboratorsRequest\x1a .proto.ListCollaboratorsResponseB\x11Z\x0fks-proto/pkg/pbb\x06proto3"

var (
	file_repo_proto_rawDescOnce sync.Once
	file_repo_proto_rawDescData []byte
)

func file_repo_proto_rawDescGZIP() []byte {
	file_repo_proto_rawDescOnce.Do(func() {
		file_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)))
	})
	return file_repo_proto_rawDescData
}

var file_repo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_repo_proto_goTypes = []any{
	(RepoVisibility)(0),                // 0: proto.RepoVisibility
	(CollaboratorRole)(0),              // 1: proto.CollaboratorRole
	(*Repo)(nil),                       // 2: proto.Repo
	(*Collaborator)(nil),               // 3: proto.Collaborator
	(*CreateRepoRequest)(nil),          // 4: proto.CreateRepoRequest
	(*CreateRepoResponse)(nil),         // 5: proto.CreateRepoResponse
	(*GetRepoRequest)(nil),             // 6: proto.GetRepoRequest
	(*GetRepoResponse)(nil),            // 7: proto.GetRepoResponse
	(*UpdateRepoRequest)(nil),          // 8: proto.UpdateRepoRequest
	(*UpdateRepoResponse)(nil),         // 9: proto.UpdateRepoResponse
	(*DeleteRepoRequest)(nil),          // 10: proto.DeleteRepoRequest
	(*DeleteRepoResponse)(nil),         // 11: proto.DeleteRepoResponse
	(*ListUserReposRequest)(nil),       // 12: proto.ListUserReposRequest
	(*ListPublicReposRequest)(nil),     // 13: proto.ListPublicReposRequest
	(*ListPublicReposResponse)(nil),    // 14: proto.ListPublicReposResponse
	(*ListUserReposResponse)(nil),      // 15: proto.ListUserReposResponse
	(*AddCollaboratorRequest)(nil),     // 16: proto.AddCollaboratorRequest
	(*AddCollaboratorResponse)(nil),    // 17: proto.AddCollaboratorResponse
	(*UpdateCollaboratorRequest)(nil),  // 18: proto.UpdateCollaboratorRequest
	(*UpdateCollaboratorResponse)(nil), // 19: proto.UpdateCollaboratorResponse
	(*RemoveCollaboratorRequest)(nil),  // 20: proto.RemoveCollaboratorRequest
	(*RemoveCollaboratorResponse)(nil), // 21: proto.RemoveCollaboratorResponse
	(*ListCollaboratorsRequest)(nil),   // 22: proto.ListCollaboratorsRequest
	(*ListCollaboratorsResponse)(nil),  // 23: proto.ListCollaboratorsResponse
}
var file_repo_proto_depIdxs = []int32{
	0,  // 0: proto.Repo.visibility:type_name -> proto.RepoVisibility
	1,  // 1: proto.Collaborator.role:type_name -> proto.CollaboratorRole
	0,  // 2: proto.CreateRepoRequest.visibility:type_name -> proto.RepoVisibility
	2,  // 3: proto.CreateRepoResponse.repo:type_name -> proto.Repo
	2,  // 4: proto.GetRepoResponse.repo:type_name -> proto.Repo
	1,  // 5: proto.GetRepoResponse.my_role:type_name -> proto.CollaboratorRole
	0,  // 6: proto.UpdateRepoRequest.visibility:type_name -> proto.RepoVisibility
	2,  // 7: proto.UpdateRepoResponse.repo:type_name -> proto.Repo
	2,  // 8: proto.ListPublicReposResponse.repos:type_name -> proto.Repo
	2,  // 9: proto.ListUserReposResponse.repos:type_name -> proto.Repo
	1,  // 10: proto.AddCollaboratorRequest.role:type_name -> proto.CollaboratorRole
	1,  // 11: proto.UpdateCollaboratorRequest.role:type_name -> proto.CollaboratorRole
	3,  // 12: proto.ListCollaboratorsResponse.collaborators:type_name -> proto.Collaborator
	4,  // 13: proto.RepoService.CreateRepo:input_type -> proto.CreateRepoRequest
	6,  // 14: proto.RepoService.GetRepo:input_type -> proto.GetRepoRequest
	8,  // 15: proto.RepoService.UpdateRepo:input_type -> proto.UpdateRepoRequest
	10, // 16: proto.RepoService.DeleteRepo:input_type -> proto.DeleteRepoRequest
	12, // 17: proto.RepoService.ListUserRepos:input_type -> proto.ListUserReposRequest
	13, // 18: proto.RepoService.ListPublicRepos:input_type -> proto.ListPublicReposRequest
	16, // 19: proto.RepoService.AddCollaborator:input_type -> proto.AddCollaboratorRequest
	18, // 20: proto.RepoService.UpdateCollaborator:input_type -> proto.UpdateCollaboratorRequest
	20, // 21: proto.RepoService.RemoveCollaborator:input_type -> proto.RemoveCollaboratorRequest
	22, // 22: proto.RepoService.ListCollaborators:input_type -> proto.ListCollaboratorsRequest
	5,  // 23: proto.RepoService.CreateRepo:output_type -> proto.CreateRepoResponse
	7,  // 24: proto.RepoService.GetRepo:output_type -> proto.GetRepoResponse
	9,  // 25: proto.RepoService.UpdateRepo:output_type -> proto.UpdateRepoResponse
	11, // 26: proto.RepoService.DeleteRepo:output_type -> proto.DeleteRepoResponse
	15, // 27: proto.RepoService.ListUserRepos:output_type -> proto.ListUserReposResponse
	14, // 28: proto.RepoService.ListPublicRepos:output_type -> proto.ListPublicReposResponse
	17, // 29: proto.RepoService.AddCollaborator:output_type -> proto.AddCollaboratorResponse
	19, // 30: proto.RepoService.UpdateCollaborator:output_type -> proto.UpdateCollaboratorResponse
	21, // 31: proto.RepoService.RemoveCollaborator:output_type -> proto.RemoveCollaboratorResponse
	23, // 32: proto.RepoService.ListCollaborators:output_type -> proto.ListCollaboratorsResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_repo_proto_init() }
func file_repo_proto_init() {
	if File_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_proto_goTypes,
		DependencyIndexes: file_repo_proto_depIdxs,
		EnumInfos:         file_repo_proto_enumTypes,
		MessageInfos:      file_repo_proto_msgTypes,
	}.Build()
	File_repo_proto = out.File
	file_repo_proto_goTypes = nil
	file_repo_proto_depIdxs = nil
}
