project:
  name: user-server
  version: v0.0.0

logger:
  level: info
  dir: "./logs"
  max_size: 100
  max_backups: 3
  max_age: 7
  compress: true
  local_time: true

database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: knowsync
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 5m

redis:
  addrs:
    - "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 1

email:
  smtp_host: "smtp.163.com"
  smtp_port: 465
  username: "your_email@163.com"
  password: "your_auth_code"
  from_address: "your_email@163.com"
  from_name: "KnowSync"

grpc:
  port: 50051
